### ISSUE TITLE
Integrate Passport authentication strategies

### ISSUE THREAD

**Issue by SirTangent** [ideahackers/ideahack.club#4]
- ```/login``` Should have a username/email and password form. As of now, use **passport-local** as the authentification strategy with Passport.js. The form action will point to ```POST /login``` where the route arrow function will validate and check the password with the database. Remember to reference the crud app repo for help and be wise, make salts ;)

- ```/register``` Already have the form (feel free to make front-end enhancements). The email input must be validated for a .edu extension. If so, use form control feedback with text below the form saying ```School: <name of the school with associated .edu>```. Form action makes POST request to ```/register``` which validates all inputs, checks if associated email already has an account, and adds an entry account to the database with their account status being ```UNDER_REVIEW```.

**Comment by 1fabunicorn** [comment]
See https://github.com/ideahackers/ideahack.club/commit/80ee8fc72c7527eaacad865d85b7f042a1cca8a6
