### ISSUE TITLE
Add CRUD Functionality for Events

### ISSUE THREAD

**Issue by SirTangent** [ideahackers/ideahack.club#5]
### You can create these routes:

- ```GET /``` The side events div should act as a small feed for upcoming events. Settings for how the events feed is displayed should be accessible in ```GET /events``` route for any accounts with admin privileges.

- ```GET /events```Will display all events, perhaps in a grid of cards, with filtering functionality. Below is the HTML element for the current event format

```
<div class="card border mb-2 border-success">
                        <img class="card-img-top" src="https://media.eggs.ca/assets/RecipePhotos/_resampled/FillWyIxMjgwIiwiNzIwIl0/Fluffy-Pancakes-New-CMS.jpg" alt="Card image cap">
                        <div class="card-body">
                            <p class="font-weight-light">June 3rd - 8:30 AM</p>
                            <h5 class="card-title">Breakfast Get Together</h5>
                            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                            <a href="#" class="btn btn-outline-warning m-1">Attend</a>
                            <a href="#" class="btn btn-outline-info m-1">More Info</a>
                        </div>
                    </div>
```
**NOTE: ALL ROUTES BELOW REQUIRE ACCESS CONTROL BASED ON USERS AND PRIVILAGES**

- ```GET /event:id``` This route will show a page for an individual event, which will contain more information than the cards under ```/events```. Note that :id is a parameter which can be read in the backend. As for now, an event page should contain: header/title, thumbnails, description, date, location, and a form of contact to ask questions. Keep in mind that the event id may not exist on the DB or the event is set to private, so provide **access control** to these routes.

- ```GET /events/create``` This page is a form to create an event. **Access granted** only for registered users. As of now, events are not public until an admin review and approves the event.
- ```POST /events/create``` This is the action for submitting a form from ```GET /events/add```

- ```GET /events/edit:id``` This page is an edit form for an event. **Access granted** only for admins and user who created or is a moderator of the event.
- ```POST /events/edit:id``` This is the action for submitting a form from ```GET /events/edit:id```

- ```POST /events/delete:id``` When this action is called, assuming the user is admin or creator, it will delete the event from the database. UI for deleting should be provided in ```GET /events/edit:id``` with confirmation dialogs.

**Comment by 1fabunicorn** [comment]
See [Backend Branch](https://github.com/ideahackers/ideahack.club/tree/backend)
