### ISSUE TITLE
Add route for password reset

### ISSUE THREAD

**Issue by SirTangent** [ideahackers/ideahack.club#8]
Create the following routes as requested by the front-end:

```GET /user/reset```: When requested, the backend will send a verification email that provides either a 'secure' link to a password reset form or provides a temporary password that is randomly generated (whatever is easier).

Note: feel free to call the route anything else if you don't like ```/user/reset```.

**Comment by 1fabunicorn** [comment]
> Create the following routes as requested by the front-end:

Thanks! Said as it should be!!!

**Comment by 1fabunicorn** [comment]
Done. Please check out the reset-testing branch

See https://github.com/ideahackers/ideahack.club/commit/80ee8fc72c7527eaacad865d85b7f042a1cca8a6
